[build]
  command = """
    curl -LsSf https://astral.sh/uv/install.sh | sh
    ~/.cargo/bin/uv sync --group docs
    ~/.cargo/bin/uv run mkdocs build
  """
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.11"
